# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bbafdefd4a3779ca2852be3d56a948ef252a7446e5b461484291d474ac4a5559c6aa639636c39e9545840e3b2d26bb01ef68685be956301783ad7cc918185a8

test:
  secret_key_base: 9bc62075f0c0926524590c276e28d3609fe3ef4e484a6fb7d5d644222cfe78dfe914003850985bb983e26bafcac9797400238461417b40f8f25d45f0244295ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
